version: "3.9"

networks:
  app-network:

services:

  app:
    image: endesapt/node-js-app:$IMAGE_TAG
    networks:
      - app-network
  
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network
