apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: "endesapt/node-js-app:{{.Values.image.tag}}"
        resources:
          requests:
            memory: "64Mi"   # Minimum memory request
            cpu: "100m"      # Minimum CPU request
          limits:
            memory: "128Mi"  # Maximum memory limit
            cpu: "150m"      # Maximum CPU limit
        ports:
        - containerPort: 80
