name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set tag var
        id: vars
        run: echo docker_tag=$(echo $(git rev-parse --short "$GITHUB_SHA")) >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push node.js server
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: endesapt/node-js-app:${{ steps.vars.outputs.docker_tag }}
