name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: server
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push node.js server
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:server"
          push: true
          tags: endesapt/node-js-app:${{ github.sha }} , endesapt/node-js-app:latest
  change_version:
    needs: docker
    runs-on: server
    steps:
        -
          name: Restart docker compose with new container
          run: |
            echo ${{ secrets.USERPWD }} | sudo -S -E docker compose -f ~/docker-compose.yml up -d



